// autogenerated file, do not change. ./scripts/track-footway-path.py > style/track-footway-path.mss

@track-width-z13:       1.3;
@footway-width-z13:       0.9;
@path-width-z13:       0.5;

@track-width-z14:       1.7;
@footway-width-z14:       1.3;
@path-width-z14:       0.9;

@track-width-z15:       2.3;
@footway-width-z15:       1.7;
@path-width-z15:       1.3;

@track-width-z16:       2.5;
@footway-width-z16:       2.0;
@path-width-z16:       1.5;

@track-width-z18:       3.0;
@footway-width-z18:       2.5;
@path-width-z18:       1.7;

@track-width-z19:       3.5;
@footway-width-z19:       3.0;
@path-width-z19:       2.0;

